[versions]
activityKtx = "1.8.2"
agp = "8.10.1"
cameraCore = "1.3.1"
cardview = "1.0.0"
fastjson = "2.0.59"
fragmentKtx = "1.6.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
activity = "1.11.0"
material = "1.13.0"
constraintlayout = "2.2.1"
preferenceKtx = "1.2.1"
recyclerview = "1.3.2"
securityCrypto = "1.1.0"
twetalkAndroid = "1.1.6-SNAPSHOT"
twetalkAndroidTrtc = "1.0.8-SNAPSHOT"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
twetalk-android = { module = "com.tencent.twetalk:twetalk-android", version.ref = "twetalkAndroid" }
twetalk-android-trtc = { module = "com.tencent.twetalk:twetalk-android-trtc", version.ref = "twetalkAndroidTrtc" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

